language: java
jdk:
- oraclejdk8
sudo: false
script: mvn clean install 
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: 
  file: "target/jarql-1.0-SNAPSHOT.jar"
  on:
    repo: jarql/jarql
